name: Workflow dispatch

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TARGET_NAME: rep_disp.yml

    steps:
      - name: Get previous ${{ env.TARGET_name }} run id
        run: |
          curl -s \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/${TARGET_NAME}/runs" \
              | jq 'if (.workflow_runs|length) == 0
                    then 0 else .workflow_runs[0].id end' _ \
              | sed 's/^/PREV_RUN_ID=/' >> "$GITHUB_ENV"
      
      - name: Print PREV_RUN_ID
        run: echo "$PREV_RUN_ID" 
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: test

      - name: Wait for the end of ${{ env.TARGET_NAME }}
        run: |
          while :
          do
            echo "try:$[i++]"
            curl -s \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/${TARGET_NAME}/runs" > _

            {
              [ "$(jq '.workflow_runs|length' _)" -eq 0 ] \
              || [ "$(jq '.workflow_runs[0].id' _)" = "$PREV_RUN_ID" ]
            } && sleep "$[RANDOM%3+3]" && continue

            status="$(jq -r '.workflow_runs[0].status' _)"
            echo "status: $status"
            [ "$status" = 'completed' ] && break
            sleep "$[RANDOM%3+3]"
          done

      - name: Print the conclusion of ${{ env.TARGET_NAME }}
        run: jq '.workflow_runs[0]|.conclusion' _
